mento-protocol/airgrab-interface

src/components/faq.tsx
src/components/verify-and-claim.tsx
src/lib/constants.ts

- This change will update the FAQ questions and answers.
- None
- None
- Fixes #71 
- N/A
- N/A

refactor: update faqs

---

src/app/terms/page.tsx
src/components/terms-modal.tsx

Update the terms and conditions based on the [latest doc](https://docs.google.com/document/d/1YoZso9nGQyEG0-taEttAdC2V2dJUUxPd/edit) from Sandra.

chore: update terms and conditions

---

src/app/layout.tsx

This PR aims to fix the gradient that breaks the mobile view after accepting T&C by removing it.
**Tested**
Looks good on mobile preview now.
**Fixes**
#88

fix: remove one gradient on mobile

---

src/components/header/header-nav.tsx

Self explanatory
**Tested**
Go to preview, click on the Team button on the Navbar
**Fixes**
https://github.com/mento-protocol/mento-general/issues/389

feat: open team on new tab

---

package.json
pnpm-lock.yaml

This PR aims to fix the rainbowkit connection issue by locking the versions
**Tested**
Tested on a preview
**Fixes**
https://github.com/mento-protocol/airgrab-interface/issues/92

chore: lock rainbowkit ver

---

src/components/verify-and-claim.tsx

Update claim text to explain more how tokens are unlocked and voting. 
Closes https://github.com/mento-protocol/mento-general/issues/397

refactor: use clearer language in claim text

---

src/components/verify-and-claim.tsx

Removes the amount from the claim button.
**Fixes**
https://github.com/mento-protocol/mento-general/issues/392

feat: remove claim amount

---

src/components/faq.tsx

Update FAQ to have the correct supply percent
**Fixes**
#107

fix: supply percent

---

src/lib/wagmi.ts

This PR adds frame wallet to the list of wallets

Feat: Added Frame wallet

---

src/app/allocation/page.tsx

- Update to use the correct FAQ link under KYC start button

fix: update kyc faq link

---

src/app/kyc-pending/page.tsx

Fixes the wording to match the text in the ticket #127 
fixes #127 
preview:

feat: update wording on KYC pending

---

src/contexts/rainbowkit-siwe-iron-session-provider.tsx

This PR adds a redirect login to redirect users who have already claimed to the claim page
N/A
N/A

Feat: Redirect early if has claimed

---

pnpm-lock.yaml
src/app/allocation/page.tsx

Fix an extra variable introduced when resolving conflicts.

fix: merge issues

---

src/app/allocation/page.tsx

fix: not allocation display check

---

src/components/footer.tsx
src/components/header/header-nav.tsx
src/components/mobile-accordion-menu.tsx
src/lib/constants.ts

This PR updates footer + header

Fix: update footer

---

src/app/allocation/page.tsx
src/lib/constants.ts

Add text to link to additional address tutorial:
[Tutorial](https://www.mentolabs.xyz/blog/how-to-claim-mento-with-another-address)

feat: link to additional address instructions

---

src/app/allocation/page.tsx
src/lib/constants.ts

Add text to link to additional address tutorial:
[Tutorial](https://www.mentolabs.xyz/blog/how-to-claim-mento-with-another-address)

feat: link to additiona address post

---

src/components/verify-and-claim.tsx
src/lib/constants.ts

Adds a link to the post ["Welcome to the Mento community"](https://www.mentolabs.xyz/blog/welcome-to-the-mento-community) on the successful claim page. This page has instructions on how users can check their veMento post claim and introduces Mento governance

feat: link to welcome post

---

src/app/allocation/page.tsx
src/lib/constants.ts

Adds a CTA on the allocation page for the user to add an additional wallet. 
- Fixes #171

feat: add wallet cta on allocation

---

src/hooks/use-claim-mento.tsx

This PR adds gas estimation to the claim & lock contract call, which should solve the issue Celo Terminal users face. After these changes, I've [claimed on Alfajores](https://alfajores.celoscan.io/tx/0x18ad478332d577ecd68fb3e7e3d77fdbc1d66164a06021bb16b18553afd74c6c), but as Celo Terminal can't easily connect to Alfajores, the only way to know if it works is to claim on mainnet. I have a wallet loaded up in Celo Terminal and am ready to test claiming; once I've confirmed it's fixed, I'll create a new PR to clean up this implementation. If we face the worst-case scenario and the app is broken, we can simply assign the previous deployment ( now current) as the production deployment with a few clicks on Vercel. 
Fixes #172

fix: add gas estimate to claim & lock call

---

src/hooks/use-claim-mento.tsx
src/hooks/use-estimate-gas.ts
src/lib/wagmi.ts

This PR refactors the gas estimation changes made in #176. It cleans up the gas estimation logic, moving it into a dedicated hook.
fixes #172

Fix: Estimate gas for claim refactor

---

src/hooks/use-claim-mento.tsx
src/hooks/use-estimate-gas.ts

Fixes the bug that blocks KYCed users from claiming.
Exact issue could not be identified, so it reverts the recent changes to the problematic function.
Tested locally with testing accounts, both KYC and KYB claims reverts with contract errors so should work on prod.
fixes  #185

fix: estimate gas bug
